import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar.js"
import ThemeToggle from "@/components/ThemeToggle.js"
import Footer from "@/components/footer.js"
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
		
      <body className="w-screen min-h-screen">
      <Navbar/>
      <div className="relative  z-10 top-30 w-full ">
      <Script
  src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
  strategy="afterInteractive"
/>
		{children}
		<Footer/>
      </div>
      
      <ThemeToggle/>
      </body>
    </html>
  );
}
